service: chaseweb

custom:
  bucket: syon-chase

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  pocketoauthrequest:
    handler: handler.pocketOauthRequest
    events:
      - http:
          path: pocket/oauth/request
          method: post
          cors: true
  pocketoauthauthorize:
    handler: handler.pocketOauthAuthorize
    events:
      - http:
          path: pocket/oauth/authorize
          method: post
          cors: true
  pocketget:
    handler: handler.pocketGet
    events:
      - http:
          path: pocket/get
          method: post
          cors: true
  librainfo:
    handler: handler.libraInfo
    events:
      - http:
          path: libra/info
          method: get
          cors: true
  librathumb:
    handler: handler.libraThumb
    events:
      - http:
          path: libra/thumb
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
