service: chaseweb

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

functions:
  pocketoauthrequest:
    handler: handler.pocketOauthRequest
    events:
      - http:
          path: pocket/oauth/request
          method: post
          cors: true
  pocketoauthauthorize:
    handler: handler.pocketOauthAuthorize
    events:
      - http:
          path: pocket/oauth/authorize
          method: post
          cors: true
  pocketget:
    handler: handler.pocketGet
    events:
      - http:
          path: pocket/get
          method: post
          cors: true
  librainfo:
    handler: handler.libraInfo
    events:
      - http:
          path: libra/info
          method: get
          cors: true
