service: chaseweb

plugins:
  - serverless-webpack

custom:
  bucket: syon-chase

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  pocketoauthrequest:
    handler: handler.pocketOauthRequest
    events:
      - http:
          path: pocket/oauth/request
          method: post
          cors: true
  pocketoauthauthorize:
    handler: handler.pocketOauthAuthorize
    events:
      - http:
          path: pocket/oauth/authorize
          method: post
          cors: true
  pocketget:
    handler: handler.pocketGet
    events:
      - http:
          path: pocket/get
          method: post
          cors: true
  pocketsendarchive:
    handler: handler.pocketSendArchive
    events:
      - http:
          path: pocket/send/archive
          method: get
          cors: true
  pocketsendfavorite:
    handler: handler.pocketSendFavorite
    events:
      - http:
          path: pocket/send/favorite
          method: get
          cors: true
  pocketsendunfavorite:
    handler: handler.pocketSendUnfavorite
    events:
      - http:
          path: pocket/send/unfavorite
          method: get
          cors: true
  pocketsendtagsadd:
    handler: handler.pocketSendTagsAdd
    events:
      - http:
          path: pocket/send/tags/add
          method: get
          cors: true
  userregister:
    handler: handler.userregister
    events:
      - http:
          path: user/register
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
      DEBUG: chase:*
  userprepare:
    handler: handler.userprepare
    events:
      - http:
          path: user/prepare
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
      DEBUG: chase:*
  librainfo:
    handler: handler.libraInfo
    events:
      - http:
          path: libra/info
          method: get
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
      DEBUG: chase:*
  librathumb:
    handler: handler.libraThumb
    events:
      - http:
          path: libra/thumb
          method: post
          cors: true
    environment:
      BUCKET: ${self:custom.bucket}
      DEBUG: chase:*
