service: chaseweb

plugins:
  - serverless-dotenv-plugin

custom:
  bucket: syon-chase

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}"
        - "arn:aws:s3:::${self:custom.bucket}/*"
  environment:
    BUCKET: ${self:custom.bucket}
    DEBUG: chase:*
    POCKET_CONSUMER_KEY: ${env:STAGE}

package:
  exclude:
    - test/**

functions:
  pocketoauthrequest:
    handler: handler.pocketOauthRequest
    events:
      - http:
          path: pocket/oauth/request
          method: post
          cors: true
  pocketoauthauthorize:
    handler: handler.pocketOauthAuthorize
    events:
      - http:
          path: pocket/oauth/authorize
          method: post
          cors: true
  pocketget:
    handler: handler.pocketGet
    events:
      - http:
          path: pocket/get
          method: post
          cors: true
  pocketprogress:
    handler: handler.pocketProgress
    events:
      - http:
          path: pocket/progress
          method: post
          cors: true
    timeout: 30
  pocketsendarchive:
    handler: handler.pocketSendArchive
    events:
      - http:
          path: pocket/send/archive
          method: get
          cors: true
  pocketsendfavorite:
    handler: handler.pocketSendFavorite
    events:
      - http:
          path: pocket/send/favorite
          method: get
          cors: true
  pocketsendunfavorite:
    handler: handler.pocketSendUnfavorite
    events:
      - http:
          path: pocket/send/unfavorite
          method: get
          cors: true
  pocketsendtagsadd:
    handler: handler.pocketSendTagsAdd
    events:
      - http:
          path: pocket/send/tags/add
          method: get
          cors: true
  userlogin:
    handler: handler.userlogin
    events:
      - http:
          path: user/login
          method: post
          cors: true
  userprepare:
    handler: handler.userprepare
    events:
      - http:
          path: user/prepare
          method: post
          cors: true
    timeout: 120
    environment:
      DEBUG: chase:*,-chase:libra-adaptor
  librainfo:
    handler: handler.libraInfo
    events:
      - http:
          path: libra/info
          method: get
          cors: true
    timeout: 10
  librathumb:
    handler: handler.libraThumb
    events:
      - http:
          path: libra/thumb
          method: post
          cors: true
    timeout: 10
